name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Puppeteer and Required Packages
        run: |
          npm init -y
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Run Puppeteer to Get Cookies
        run: node get-cookies.js

      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        
        
      - name: Run API tests with valid cookies
        run: |
          postman collection run "43090239-6915ce11-d726-470b-b976-e8a1452aa128" `
            -e "43090239-081846a6-422f-4e26-880e-a9272e5901f1" `
            --env-var "cookies=$(cat cookies.txt)"

      
      - name: Run API tests with valid cookies
        run: |
          postman collection run "43090239-6915ce11-d726-470b-b976-e8a1452aa128" `
            -e "43090239-081846a6-422f-4e26-880e-a9272e5901f1" `
            --iteration-data "./data.csv"

        
